# Generated by Django 2.2.7 on 2020-08-12 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='velogcomment',
            old_name='VelogComment',
            new_name='velogComment',
        ),
    ]
