# Generated by Django 2.2.7 on 2020-07-28 07:03

import api.contests.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contests', '0001_initial'),
        ('communications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='default.png', null=True, upload_to=api.contests.utils.user_profile_image_path)),
                ('email', models.EmailField(max_length=254)),
                ('phoneNumber', models.CharField(blank=True, max_length=11, null=True)),
                ('nickname', models.CharField(blank=True, max_length=255, null=True)),
                ('contestRankDictionary', models.TextField(default='{}')),
                ('codeNoteScraps', models.ManyToManyField(blank=True, null=True, to='communications.ContestCodeNote')),
                ('contestScrpas', models.ManyToManyField(blank=True, null=True, to='contests.Contest')),
                ('debateScraps', models.ManyToManyField(blank=True, null=True, to='communications.ContestDebate')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('velogScraps', models.ManyToManyField(blank=True, null=True, to='communications.Velog')),
            ],
        ),
    ]
