# Generated by Django 2.2.7 on 2020-07-28 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='codeNoteScraps',
            field=models.ManyToManyField(blank=True, to='communications.ContestCodeNote'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='contestScrpas',
            field=models.ManyToManyField(blank=True, to='contests.Contest'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='debateScraps',
            field=models.ManyToManyField(blank=True, to='communications.ContestDebate'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='velogScraps',
            field=models.ManyToManyField(blank=True, to='communications.Velog'),
        ),
    ]
