# Generated by Django 2.2.7 on 2020-07-31 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200731_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='codeNoteScraps',
            field=models.ManyToManyField(blank=True, related_name='scrapProfiles', to='communications.ContestCodeNote'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='debateScraps',
            field=models.ManyToManyField(blank=True, related_name='scrapProfiles', to='communications.ContestDebate'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='velogScraps',
            field=models.ManyToManyField(blank=True, related_name='scrapProfiles', to='communications.Velog'),
        ),
    ]
