# Generated by Django 2.2.7 on 2020-08-05 01:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communications', '0001_initial'),
        ('contests', '0003_auto_20200803_2211'),
        ('users', '0007_auto_20200731_1816'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='CustomProfile',
        ),
    ]
