# Generated by Django 2.2.7 on 2020-08-05 04:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200805_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='customprofile',
            name='createdAT',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customprofile',
            name='updatedAT',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
