# Generated by Django 2.2.7 on 2020-08-05 07:00

import api.contests.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200805_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='customprofile',
            name='smallImage',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=api.contests.utils.user_profile_image_path),
        ),
    ]
