# Generated by Django 2.2.7 on 2020-08-07 08:12

import api.contests.utils
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_customprofile_smallimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customprofile',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=api.contests.utils.user_profile_image_path),
        ),
        migrations.AlterField(
            model_name='customprofile',
            name='smallImage',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=api.contests.utils.user_profile_image_path),
        ),
    ]
