# Generated by Django 2.2.7 on 2020-08-12 09:13

import api.contests.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('educations', '0006_auto_20200812_1059'),
        ('users', '0011_auto_20200807_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='customprofile',
            name='isConsentingEmail',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customprofile',
            name='isConsentingSMS',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customprofile',
            name='isRealNameAuthenticated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customprofile',
            name='lecturePackages',
            field=models.ManyToManyField(to='educations.LecturePackage'),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('createdAT', models.DateTimeField(auto_now_add=True)),
                ('updatedAT', models.DateTimeField(auto_now=True)),
                ('smallImage', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=api.contests.utils.user_profile_image_path)),
                ('members', models.ManyToManyField(related_name='teams', to=settings.AUTH_USER_MODEL)),
                ('representative', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='representingTeam', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
