# Generated by Django 2.2.7 on 2020-08-12 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20200812_1813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customprofile',
            old_name='contestScrpas',
            new_name='contestScraps',
        ),
    ]
