# Generated by Django 2.2.7 on 2020-08-13 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20200812_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customprofile',
            name='lecturePackages',
            field=models.ManyToManyField(blank=True, null=True, to='educations.LecturePackage'),
        ),
    ]
