# Generated by Django 2.2.7 on 2020-08-13 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20200813_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customprofile',
            name='lecturePackages',
            field=models.ManyToManyField(blank=True, to='educations.LecturePackage'),
        ),
    ]
