# Generated by Django 2.2.7 on 2020-08-13 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20200813_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='createdAT',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='updatedAT',
            new_name='updatedAt',
        ),
    ]
