# Generated by Django 2.2.7 on 2020-08-13 09:12

import api.contests.utils
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20200813_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='smallImage',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='user_6/profile.png', null=True, upload_to=api.contests.utils.user_profile_image_path),
        ),
    ]
