# Generated by Django 2.2.7 on 2020-08-13 10:04

import api.contests.utils
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20200813_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='smallImage',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='user_6/profile', null=True, upload_to=api.contests.utils.team_profile_image_path),
        ),
    ]
