# Generated by Django 2.2.7 on 2020-08-13 10:14

import api.contests.utils
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20200813_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customprofile',
            name='smallImage',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='/media/user_6/profile_LdXQFC4.png', null=True, upload_to=api.contests.utils.user_profile_image_path),
        ),
    ]
