# Generated by Django 2.2.7 on 2020-08-14 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_teaminvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='teaminvite',
            name='isAccepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teaminvite',
            name='isFinished',
            field=models.BooleanField(default=False),
        ),
    ]
