# Generated by Django 2.2.7 on 2020-07-30 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eduvideolecture',
            name='writer',
        ),
    ]
