# Generated by Django 2.2.7 on 2020-08-10 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('educations', '0003_eduvideolecture_writer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eduvideolecture',
            name='isCharged',
        ),
        migrations.CreateModel(
            name='LecuturePackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('hitNums', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=255)),
                ('isCharged', models.BooleanField(default=False)),
                ('packageExplanation', models.TextField(blank=True, null=True)),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='eduvideolecture',
            name='lecuturePackage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='educations.LecuturePackage'),
        ),
    ]
