# Generated by Django 2.2.7 on 2020-08-12 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educations', '0005_auto_20200810_1953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eduvideolecture',
            old_name='lecuturePackage',
            new_name='lecturePackage',
        ),
    ]
