# Generated by Django 2.2.7 on 2020-08-03 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contest',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='contest',
            old_name='evliationMethod',
            new_name='evaluationMethod',
        ),
        migrations.RenameField(
            model_name='contest',
            old_name='updated_at',
            new_name='updatedAt',
        ),
        migrations.RenameField(
            model_name='contestuseranswer',
            old_name='constest',
            new_name='contest',
        ),
    ]
