# Generated by Django 2.2.7 on 2020-08-03 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_auto_20200803_2209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contestfile',
            old_name='constest',
            new_name='contest',
        ),
    ]
