# Generated by Django 2.2.7 on 2020-08-07 07:45

import api.contests.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0003_auto_20200803_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestuseranswer',
            name='file',
            field=models.FileField(upload_to=api.contests.utils.user_answer_upload_to),
        ),
    ]
