# Generated by Django 2.2.7 on 2020-08-07 07:58

import api.contests.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0004_auto_20200807_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestuseranswer',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=api.contests.utils.user_answer_upload_to),
        ),
    ]
