# Generated by Django 2.2.7 on 2020-08-07 08:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0005_auto_20200807_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='subtitle',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
