# Generated by Django 2.2.7 on 2020-08-07 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0006_contest_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
