# Generated by Django 2.2.7 on 2020-08-07 08:46

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0007_auto_20200807_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='profileThumb',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='contestuseranswer',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
