# Generated by Django 2.2.7 on 2020-08-07 08:52

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0008_auto_20200807_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestfile',
            name='profileThumb',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=''),
        ),
    ]
