# Generated by Django 2.2.7 on 2020-08-07 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0009_contestfile_profilethumb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='backThumb',
        ),
        migrations.RemoveField(
            model_name='contestfile',
            name='profileThumb',
        ),
    ]
