# Generated by Django 2.2.7 on 2020-08-10 02:10

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0010_auto_20200807_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='backThumb',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=''),
        ),
    ]
