# Generated by Django 2.2.7 on 2020-08-10 07:27

import api.contests.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0011_contest_backthumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[api.contests.validators.validate_file_size]),
        ),
    ]
