# Generated by Django 2.2.7 on 2020-08-10 08:45

import api.contests.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0012_auto_20200810_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='contestuseranswer',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[api.contests.validators.validate_file_size]),
        ),
    ]
