# Generated by Django 2.2.7 on 2020-08-14 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_teaminvite'),
        ('contests', '0013_auto_20200810_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestuseranswer',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teamAnswer', to='users.Team'),
        ),
    ]
