# Generated by Django 2.2.7 on 2020-08-14 09:02

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0014_contestuseranswer_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='backThumb',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='user_1/profile', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='contest',
            name='profileThumb',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='user_1/profile', null=True, upload_to=''),
        ),
    ]
