# Generated by Django 2.2.7 on 2020-08-05 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commenttoquestion',
            name='hitNums',
        ),
    ]
